repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
    - id: gitleaks
